---

- name: "[Firewall Config Kibana Logstash and Fleet Server] Configure firewall TCP"
  ansible.builtin.firewalld:
    state: enabled
    port: "{{ item }}/tcp"
    zone: public
    immediate: yes
    permanent: yes
  with_items: "{{ allowed_tcp_ports }}"
  when: allowed_tcp_ports is defined

- name: "[Firewall Config Kibana Logstash and Fleet Server] Configure firewall UDP"
  ansible.builtin.firewalld:
    state: enabled
    port: "{{ item }}/udp"
    zone: public
    immediate: yes
    permanent: yes
  with_items: "{{ allowed_udp_ports }}"
  when: allowed_udp_ports is defined
  