---
# URL for download repository install file for Rocky 9. You can get this URL on this page - https://www.zabbix.com/download in "Zabbix Packages" section.
zabbix_repo_package_url_rocky9: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm