---
# URL Kibana package location
enterprise_search_package_url: "http://nginx.itproblog.ru/enterprise-search-8.13.2.rpm"
enterprise_search_version: "{{ enterprise_search_package_url | regex_search('\\d\\.\\d+\\.\\d+') }}"

# Password of "elastic" user
elastic_user: "elastic"

# Password of "elastic" user
elastic_user_password: "{{ lookup('env','ELASTIC_USER_PWD') }}"

# URL of Elasticsearch server
elasticsearch_url: "https://elk01.plex.local:9200"

# Kibana listen url
kibana_listen_url: 'https://kibana.itproblog.ru'

# Enterprise Search configuration file location
es_config_file_location: "/usr/share/enterprise-search/config/enterprise-search.yml"

# Enterprise Search encryption key
es_encryption_key: "{{ lookup('env','ES_ENCR_KEY') }}"